* 데이터 분석 워크샵 - Python 활용법 기초

연세대학교 2018년 동계 데이터 분석 워크샵 /Python 활용법 기초/ 강의자료.


** 과정 설명

프로그래밍 언어 및 Python에 대해 배울 수 있는 자료들은 인터넷 상에서, 또는 책에서 많이 구할 수 있습니다. 하지만 전문 프로그래머를 목표로 하는 대신, 데이터 분석을 하기 위한 맥락에서 Python을 설명하는 자료들은 그보다 더 적습니다. 본 과정에서는 그 Python이라는 프로그래밍 언어와 데이터 분석이라는 두 분야의 연결지점을 다룹니다.

Python을 5일 과정에 모두 완벽하게 배우는것은 어렵습니다. 본 워크샵의 목표는 아래와 같이 잡았습니다.

 - 직접 파이썬에 뛰어들어 본다
 - 간단한 프로그램을 직접 작성해본다
 - 데이터 분석에 직접 써먹을 수 있는 예제 중심으로 진행한다
 - 워크샵이 끝난 이후에는 스스로 문서를 찾아가며 [[file:proficiency.org][점점 고수준]]의 프로그램을 작성해갈 수 있다
 - 엑셀로 하던 작업의 일부를 파이썬으로 대체할 수 있다


** 과정 특징

프로그램 언어를 익히기 위해 책이나 글만 보면서 따라해서는 중간에 막히는 부분들이 발생합니다. 그리고 막연히 어렵게 느껴지기도 하고요. 또 어떤 경우에는 눈으로만 읽는 분들이 있는데, 눈으로만 봐서는 실제로 프로그램을 작성하기가 어렵습니다. 

본 과정은 실습을 중심으로 진행합니다. 그래서, 따라할 수 있는 형태의 강의 자료가 제공됩니다. 강사가 앞에서 직접 라이브 코딩을 하면서 진행합니다. 수강하는 분들도 직접 코드를 따라서 작성할 수 있도록 자료가 온라인에 게시되기 때문에 수업을 듣지 않은 분들도 자료를 열람할 수 있지만, 실습을 진행하면서 발생하는 Q&A나 개별 1:1 지도, 각 개인의 프로젝트 목표에 대한 피드백 등은 [[file:qna.org][제한된 메일링 리스트]]를 사용하여 진행합니다.

강의 자료에서는 하나 하나의 요소에 대해 자세하게 설명하지는 않습니다. 인터넷상에 더 상세한 자료가 많이 있습니다. 여기서는 그런 정보를 습득하기보다는, 실제로 여러번 사용하면서 감을 잡는 것을 목표로 합니다. 

수강하는 분들 각각의 경험이나 실력이 제각각 다를 것입니다. 본 과정의 흐름은 프로그래밍 언어를 아예 모르는 분을 대상으로 잡았습니다. 때문에 프로그래밍 언어를 접해봤거나, Python을 접해본 분들은 초반의 언어 자체에 대한 부분은 다소 쉽게 느껴질 수 있겠습니다. 그런 분들은 앞에서 진행하는 강의를 따라오는 대신, 진행하는 데이터 분석 부분을 독자적으로 진행하셔도 좋습니다. 진행하면서 막히는 부분이나 궁금한 부분들을 [[file:qna.org][메일링 리스트에 질문]]하시면 중간의 개별 연습문제 풀이 시간이나 쉬는 시간을 사용하여 답변드립니다.


** 준비물 및 사전지식

실습을 중심으로 진행하는 워크샵이기 때문에, 수강하시는 분들은 각자 컴퓨터를 준비하셔야 합니다. OS는 맥, 윈도우, 리눅스 모두 가능합니다.

프로그래밍에 대한 사전지식이 없어도 수강할 수 있습니다.


** 강사 소개

연세대학교 컴퓨터과학과를 졸업하고, 소셜 네트워크 분석 전문 기업인 [[http://cyram.com][사이람]]에 입사하여 리서치 엔지니어 및 소프트웨어 개발자로 2년 5개월, 시스템개발팀 팀장으로 2년여간 재직하면서 소셜 네트워크 분석 소프트웨어를 개발하고 다양한 기업들의 데이터를 분석하는 프로젝트를 수행했습니다. 사이람 동료였던 김무궁, 그리고 함께 모인 다른 사람들과 [[https://play.google.com/store/apps/details?id=com.ogqcorp.bgh][오지큐]]를 공동창업하고, 5년 9개월간 CTO로 재직하며 모바일 백엔드 플랫폼을 개발했습니다. 그리고 지금은 그 경험을 토대로, 오지큐 동료였던 허민강과 함께 [[https://bothub.studio/?utm_source=github&utm_medium=display&utm_campaign=python-basic-workshop-2018][BotHub.Studio]]를 개발하며 또 다른 창업을 준비하고 있습니다.


** 과정 개요

*** 1일차: Python 배우기

 - 학습 목표 공유
 - [[file:python-overview.org][Python이란?]]
 - [[file:installation.org][개발 환경(Spyder)에 익숙해지기]]
 - [[file:language-basic-1.org][Python 기초 1]]: 출력문, 변수, 반복문, 조건문
 - [[file:language-basic-2.org][Python 기초 2]]: 자료형 (list, tuple, dict, set, str)
 - [[file:qna.org][Q&A 및 코드리뷰]]

*** 2일차: Python 배우기

 - [[file:language-basic-3.org][Python 기초 3]]: 파일 다루기, 함수, 클래스
 - [[file:language-basic-4.org][Python 기초 4]]: 모듈, 예외, 오류
 - [[file:qna.org][Q&A 및 코드리뷰]]

*** 3일차: 웹페이지 수집하기

 - [[file:web-crawling.org][웹페이지 수집하기]]
 - [[file:jupyter-install.org][Jupyter Notebook에 익숙해지기]]
 - [[file:qna.org][Q&A 및 코드리뷰]]

*** 4일차: Excel 데이터 분석하기

 - [[file:excel-1.org][엑셀 파일 다루기 1]]: 데이터 다루기
 - [[file:excel-2.org][엑셀 파일 다루기 2]]: 그래프 그리기
 - [[file:pandas.org][Pandas 깊이 배우기]]
 - [[file:qna.org][Q&A 및 코드리뷰]]

*** 5일차: 커져가는 코드 관리하기

 - 리팩토링: 함수 사용, 모듈화
 - 테스트: pytest
 - 회고 및 평가

*** Appendix

 - NumPy 배우기
 - SciPy 배우기
 - Bokeh
 - HTML에서 원하는 정보 가져오기: [[file:beautifulsoup.org][BeautifulSoup]]
 - 문자열 능숙하게 다루기: Regex (정규표현식)
 - 패키지 만들기
 - GitHub 사용하기
 - ArgumentParser 사용하기
